import type { Metadata } from "next";

import { Inter } from "next/font/google"; 
import "./globals.css"; // Importing global styles
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// Load Google font
const inter = Inter({
  subsets: ['latin'], // Specify the subsets you want to use
});

// Page metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Apply the Inter font class */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
